<a href="https://colab.research.google.com/github/Aaditya69Kumar/Numpy-Data-Analysis/blob/main/Numpy_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What programming languages does Machine Learning use?
Python, R, SQL and Scala are the most popular languages in data science and each of them has a series of libraries or dependencies that provide a different value within the process of data management, processing and analysis.

# Top Seven python Libraries for Machine learning

*  NumPy
*  Pandas
*  Matplotlib
*  Seaborn
*  Tensorflow
*  Keras
*  Scikit-learn












# NumPy: The Number Crunching Superpower for ML
Welcome! This time, we're learning NumPy - the secret engine behind ALL data science and machine learning in Python. Think of it as your ultra-fast calculator that can handle millions of numbers at once!
It also serves as a basis for other Python data science libraries and can be used to perform advanced mathematical operations such as solving systems of linear equations, generating random numbers or manipulating arrays.

# NumPy = NUMerical PYthon

In [1]:
my_list = [1,2,3,4]

In [3]:
import numpy as np
my_array = np.array([1,2,3,4])

array([2, 4, 6, 8])

In [4]:
my_list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
my_array*2

array([2, 4, 6, 8])

# Without NumPy:-

In [6]:
# Adding two lists of grades
math_grades = [85, 92, 78, 88]
science_grades = [88, 94, 82, 90]


total = []
for i in range(len(math_grades)):
    total.append(math_grades[i] + science_grades[i])
print(total)

[173, 186, 160, 178]


# With NumPy:-

In [7]:
import numpy as np

math_grades = np.array([85, 92, 78, 88])
science_grades = np.array([88, 94, 82, 90])

total = math_grades + science_grades
print(total)

[173 186 160 178]


# Creating Arrays:- four ways

In [8]:
import numpy as np

# Method 1: From list
grades = np.array([85, 92, 78, 88, 95])
print("Grades:", grades)

# Method 2: Zeros (used for ML initialization)
zeros_array = np.zeros(5)  # [0., 0., 0., 0., 0.]
print("Zeros:", zeros_array)

# Method 3: Ones
ones_array = np.ones(5)
print("Ones:", ones_array)

# Method 4: Range
range_array = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
print("Range:", range_array)

Grades: [85 92 78 88 95]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Range: [0 2 4 6 8]


# Now Let's work with some real data

In [9]:
# Create arrays for our class
student_ids = np.arange(1, 11) # what is the output of this ???
math_scores = np.array([85, 92, 78, 88, 95, 82, 76, 91, 84, 89])
science_scores = np.array([88, 94, 82, 90, 93, 85, 79, 95, 87, 92])

print("Student IDs:", student_ids)
print("Math Scores:", math_scores)
print("Science Scores:", science_scores)

Student IDs: [ 1  2  3  4  5  6  7  8  9 10]
Math Scores: [85 92 78 88 95 82 76 91 84 89]
Science Scores: [88 94 82 90 93 85 79 95 87 92]


# Vectorization in NumPy
 Vectorization in NumPy refers to applying operations on entire arrays without using explicit loops.

In [ ]:
# Find total scores


# Apply curve: add 5 points to everyone


# Calculate average for each student


# Find who needs improvement (below 80)


# Aggregation (Summary statistics)

In [10]:
print("\n--- Class Statistics ---")
print("Math average:", np.mean(math_scores))
print("Math highest:", np.max(math_scores))
print("Math lowest:", np.min(math_scores))
print("Math standard deviation:", np.std(math_scores))
print("Sum of all math scores:", np.sum(math_scores))


--- Class Statistics ---
Math average: 86.0
Math highest: 95
Math lowest: 76
Math standard deviation: 5.830951894845301
Sum of all math scores: 860


# Indexing with Conditions

In [11]:
# Find all students with math > 90
top_math_students = student_ids[math_scores > 90]
print("Top math students (ID):", top_math_students)

# Find scores of students who need help
low_scores = math_scores[math_scores < 80]
print("Low scores that need help:", low_scores)

# Multiple conditions
good_students = student_ids[(math_scores > 85) & (science_scores > 90)]
print("Good in both subjects:", good_students)

Top math students (ID): [2 5 8]
Low scores that need help: [78 76]
Good in both subjects: [ 2  5  8 10]


# Reshaping

In [12]:
# Our scores as a flat list
all_scores = np.array([85, 92, 78, 88, 95, 82, 76, 91, 84, 89,
                       88, 94, 82, 90, 93, 85, 79, 95, 87, 92])

# Reshape to 2D: 10 students × 2 subjects
score_matrix = all_scores.reshape(10, 2)
print("\nScore Matrix (Students × Subjects):")
print(score_matrix)
print("Shape:", score_matrix.shape)  # (10, 2)


Score Matrix (Students × Subjects):
[[85 92]
 [78 88]
 [95 82]
 [76 91]
 [84 89]
 [88 94]
 [82 90]
 [93 85]
 [79 95]
 [87 92]]
Shape: (10, 2)


# NumPy for Machine Learning
# Feature Matrices (x) ->

In [13]:
# In ML, data must be 2D arrays
# Each row = one student
# Each column = one feature (score, age, etc.)

# Create feature matrix for ML
X = np.array([
    [85, 20],  # Student 1: math=85, age=20
    [92, 21],  # Student 2: math=92, age=21
    [78, 22],  # Student 3: math=78, age=22
    [88, 20],  # Student 4: math=88, age=20
])

print("Feature matrix X:")
print(X)
print("Shape (rows, cols):", X.shape)

Feature matrix X:
[[85 20]
 [92 21]
 [78 22]
 [88 20]]
Shape (rows, cols): (4, 2)


# labels ->

In [14]:
# Did each student pass? (1 = Yes, 0 = No)
y = np.array([1, 1, 0, 1])  # Only student 3 failed

print("\nTarget labels y:")
print(y)


Target labels y:
[1 1 0 1]


# Random Data Generation

In [15]:
# ML needs LOTS of data to train
# NumPy can create fake data for testing

np.random.seed(42)  # The story behind ‘random.seed(42)’ in machine learning

# Create 100 fake students with random scores
fake_students = np.random.randint(60, 100, size=(100, 2))
print("\nFirst 5 fake students (math, science):")
print(fake_students[:5])


First 5 fake students (math, science):
[[98 88]
 [74 67]
 [80 98]
 [78 82]
 [70 70]]


# Key Takeway:

# NumPy arrays:-

1.   Do math on entire columns at once
2.   Filter with conditions
3.   Calculate statistics instantly
4.   Prepare data for ML models

# In Data Science:-

1.   Lists are for storing things
2.   NumPy arrays are for DOING MATH with things


